### ISSUE TITLE
CRUD Create is making duplicate blank entry into DB

### ISSUE THREAD

**Issue by jasonspick** [Laravel-Backpack/CRUD#1646]
# Bug report

### What I did:
Create new record
### What I expected to happen:
New Record to be recorded
### What happened:
Got error: `SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'id' cannot be null (SQL: update `locations` set `updated_at` = 2018-09-22 12:19:41, `id` = where `id` = 15)`

When I checked db the record I saved was there, but there was also a blank record in addition.

### What I've already tried to fix it:
Since it's saving the correct record, but creating an additional blank one, I am not sure where to look.
### Backpack, Laravel, PHP, DB version:
Backpack - 3.4
PHP  - 7.2.9
DB - google cloud sql

### Here is my CRUD Controller:
`class LocationsCrudController extends CrudController
{
    public function setup()
    {
        /*
        |--------------------------------------------------------------------------
        | CrudPanel Basic Information
        |--------------------------------------------------------------------------
        */
        $this->crud->setModel('App\Models\Locations');
        $this->crud->setRoute(config('backpack.base.route_prefix') . '/locations');
        $this->crud->setEntityNameStrings('locations', 'locations');

        /*
        |--------------------------------------------------------------------------
        | CrudPanel Configuration
        |--------------------------------------------------------------------------
        */

        // TODO: remove setFromDb() and manually define Fields and Columns
        $this->crud->setFromDb();

        // add asterisk for fields that are required in LocationsRequest
        $this->crud->setRequiredFields(StoreRequest::class, 'create');
        $this->crud->setRequiredFields(UpdateRequest::class, 'edit');

        $this->crud->removeColumns(['parent_id','partner_id','address_1','address_2','secondary_contact_id','country','zip_code','phone','mobile','fax','email','website']);

        $this->crud->addColumn([
            'name' => 'primary',
            'label' => 'Primary',
            'type' => 'boolean',
            'options' => [0 => '<i class="fa fa-ban text-danger"></i>', 1 => '<i class="fa fa-check text-success"></i>']
        ]);
        $this->crud->addColumn([
            'name' => 'disabled',
            'label' => 'Disabled',
            'type' => 'boolean',
            'options' => [0 => '<i class="fa fa-ban text-danger"></i>', 1 => '<i class="fa fa-check text-success"></i>']
        ]);
        $this->crud->addColumn([
            'label' => "Primary Contact",
            'type' => 'select',
            'name' => 'primary_contact_id', // the db column for the foreign key
            'entity' => 'PrimaryContact', // the method that defines the relationship in your Model
            'attribute' => 'name', // foreign key attribute that is shown to user
            'model' => "App\User" // foreign key model
        ]);
        $this->crud->setColumnDetails('primary_contact_id', ['attribute' => 'name']);

        $this->crud->addField([
            'label' => "Parent Company",
            'type' => 'select',
            'name' => 'parent_id', // the db column for the foreign key
            'entity' => 'Company', // the method that defines the relationship in your Model
            'attribute' => 'name', // foreign key attribute that is shown to user
            'model' => "App\Models\Locations" // foreign key model
        ]);
        $this->crud->addField([
            'label' => "Partner",
            'type' => 'select',
            'name' => 'partner_id', // the db column for the foreign key
            'entity' => 'Partner', // the method that defines the relationship in your Model
            'attribute' => 'name', // foreign key attribute that is shown to user
            'model' => "App\Models\Locations" // foreign key model
        ]);
        $this->crud->addField([
            'name' => 'primary',
            'label' => 'Primary Location / Company',
            'type' => 'checkbox'
        ]);
        $this->crud->addField([
            'name' => 'disabled',
            'label' => 'Disable',
            'type' => 'checkbox'
        ]);
        $this->crud->addField([
            'label' => "Primary Contact",
            'type' => 'select',
            'name' => 'primary_contact_id', // the db column for the foreign key
            'entity' => 'PrimaryContact', // the method that defines the relationship in your Model
            'attribute' => 'name', // foreign key attribute that is shown to user
            'model' => "App\User" // foreign key model
        ]);
        $this->crud->addField([
            'label' => "Secondary Contact",
            'type' => 'select',
            'name' => 'secondary_contact_id', // the db column for the foreign key
            'entity' => 'SecondaryContact', // the method that defines the relationship in your Model
            'attribute' => 'name', // foreign key attribute that is shown to user
            'model' => "App\User" // foreign key model
        ]);
    }

    public function store(StoreRequest $request)
    {
        // your additional operations before save here
        $redirect_location = parent::storeCrud($request);
        // your additional operations after save here
        // use $this->data['entry'] or $this->crud->entry
        return $redirect_location;
    }

    public function update(UpdateRequest $request)
    {
        // your additional operations before save here
        $redirect_location = parent::updateCrud($request);
        // your additional operations after save here
        // use $this->data['entry'] or $this->crud->entry
        return $redirect_location;
    }
}`

**Comment by jasonspick** [comment]
This is also happening on the update as well.

**Comment by AbbyJanke** [comment]
I has this issue before and while i can’t remember the exact fix it was due to the select 1 relationships. It is attempting to create a related model record. I believe had to do with the way i defined the relationship within the model

**Comment by tabacitu** [comment]
I think so too. I'd look at ```partner``` and ```company``` relationships first.

**Comment by tabacitu** [comment]
Cannot confirm the bug, so I'm going to close this, as it looks like an implementation issue. Please reopen if I'm wrong.

**Comment by jasonspick** [comment]
@AbbyJanke You are correct. I flipped from HasOne to BelongsTo and the issue is resolved.

**Comment by AbbyJanke** [comment]
Glad you got it resolved, sorry i didnt have an exact answer but the end issue is backpack not supporting all relationship types safely and think we should look into it. @tabacitu  thoughts on how we can maybe fix this or improve error output? Help better onboarding but again go back to supporting more relationship types
