### ISSUE TITLE
Text field column: limit it in table, but print the whole content in the export

### ISSUE THREAD

**Issue by masetto** [Laravel-Backpack/CRUD#3667]
Hi,
I have a text field that I'd like to show with standard character limit in table, but print the whole content in datatables export.

In `setupListOperation' or Crud Controller I added the column:
```
        $this->crud->addColumn([
            'name' => 'instruction',
            'visibleInTable' => true,
            'visibleInExport' => true,
            'limit' => 10000,
        ]);
```
The consequence is that I see a very long text in the table and it messes up the whole table.

Is there any way to limit the text in the table, but not in the export?

Thanks.

**Comment by tabacitu** [comment]
Hi @masetto ,

Not that I know of, no... The export is done using DataTables' export plugin - which only exports what is visible. So we're limited to what it can do at the moment.

We do have plans to move away from this plugin and create an Export operation, which will give us complete control over the export process and let us export tables with millions of entries (using PHP Generators), pick columns before export, have other export types, etc. But we won't be working on that in the next few months, we're currently hard at work at a few other super-cool addons which take priority. 

Until we do change the export... I really see no solution to this other than looking up the plugin and seeing if it allows anything like this. If it doesn't, you can [create an Export operation yourself](https://backpackforlaravel.com/docs/4.1/crud-operations#creating-a-custom-operation-1) that would fit your needs. Both are pretty time-consuming but to be honest I'd rather do the second, at least it's 100% guaranteed to result in what you want. If you do create an Export operation that works for you, please consider sharing your code too, at least as a copy-paste here, I'm sure someone will be SUPER thankful when they stumble upon it.

Sorry I couldn't be of more help.
Cheers!

**Comment by guleswine** [comment]
![image](https://user-images.githubusercontent.com/23197378/152657583-a52c97d0-861a-40ed-84ab-a98667513343.png)
so this problem was fixed?

**Comment by guleswine** [comment]
```/*
    |--------------------------------------------------------------------------
    | ACCESSORS
    |--------------------------------------------------------------------------
    */
    public function getOriginalMessageAttribute()
    {
        return $this->message;
    }`

`CRUD::column('message')->label('Текст')->visibleInTable(true)->visibleInExport(false);
        CRUD::column('originalmessage')->label('Текст')->limit(10000)->exportOnlyField(true);`

little hack for this problem

**Comment by pxpm** [comment]
Hello @guleswine . Not solved, just "done" as @tabacitu said this needs huge changes in datatables to make it properly work. 

I didn't think about your solution at the time, but indeed a very good one. Not fancy having twice the same column, but it works around the problem very well. 

Thank you very much for sharing @guleswine it will help someone in future I am sure. We have plans to messup with export functionality in the near future. 

Best,
Pedro
