### ISSUE TITLE
[Bug] Custom search logic for computational column

### ISSUE THREAD

**Issue by LavinaHs** [Laravel-Backpack/CRUD#3701]
# Bug report

### What I did

I am attempting to create custom sorting and search logic for a column that is calculated on select

In the public function i add an operation:

$this->crud->operation('list', function () {
            $this->crud->groupBy('email')
                ->select('*', DB::raw('count(*) as totalAttempts'));
        });
       
And then attempt to create a column:

        $this->crud->addColumn(['name' => 'totalAttempts', 'type' => 'text', 'label' => 'Login count',
            'orderable' => true,
            'orderLogic' => function ($query, $column, $columnDirection) {
                return $query->orderBy('totalAttempts', $columnDirection);
            },
            'searchLogic' => function ($query, $column, $searchTerm) {
                $query->orWhere('totalAttempts', 'like', '%'.$searchTerm.'%');
            },
        ]);
  
### What I expected to happen

I expect the column to now be sortable and searchable

### What happened

The column is sortable and  the orderLogic was able to recognize column 'lastLoginAttempt', but when adding the search logic it returns the error: "Column not found: 1054 Unknown column 'lastLoginAttempt' in 'where clause' at"

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.11 (cli) (built: Sep 29 2020 10:17:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.29.3@93f6d565a07045baa0e4b941ae1f733cd5984d65

### BACKPACK VERSION:
4.1.0@d0612499fa22d91f7302594313c60880c41c1180

**Comment by pxpm** [comment]
Hello @LavinaHs thanks for raising the issue.

I don't see where `lastLoginAttempt` comes from in your code. Also it would help if you could provide the produced `sql queries`. You can do that by appending `->toSql()` in a query instance. 

Let me know,
Pedro

**Comment by LavinaHs** [comment]
Sorry for the confusion, I updated the names lastLoginAttempt to totalAttempts after seeing the mistake while changing all variable names.
When logging initial query i get: 
select *, count(*) as totalAttempts,  from `login_attempts` group by `email`

when quering with search:
select * from `login_attempts` where `ip` like ? or `email` like ? or `totalAttempts` like ? 

the select does not take into account the column i added previously although it does get used in, while i see that if i log it on the order logic the select is:
select *, count(*) as totalAttempts from `login_attempts` group by `email` order by `lastLoginAttempt` asc limit 10

**Comment by LavinaHs** [comment]
> Sorry for the confusion, I updated the names lastLoginAttempt to totalAttempts after seeing the mistake while changing all variable names.
> When logging initial query i get:
> select _, count(_) as totalAttempts, from `login_attempts` group by `email`
> 
> when quering with search:
> select * from `login_attempts` where `ip` like ? or `email` like ? or `totalAttempts` like ?
> 
> the select does not take into account the column i added previously although it does get used in, while i see that if i log it on the order logic the select is:
> select _, count(_) as totalAttempts from `login_attempts` group by `email` order by `lastLoginAttempt` asc limit 10

**Comment by bedoz** [comment]
I'm not sure to understand your needs, but i think you want to view totalAttemps on a list o users. Isn't it?
What about using accessors?
I think creating on Model a function with logic to retrieve totalAttempts and use it like a real field on list, could be a good start.

Maybe a public function getTotalAttempsAttribute() can help on this, with query inside, but take a look at performance to avoid hundreds of query on list to get that value.

**Comment by LavinaHs** [comment]
Hello @bedoz, I have already attempted doing that, but that column is still unsortable and unsearchable, and to write custom logic, and the same problem as before as the select needs to contain column totalAttempts or custom search logic will not work. Perhaps different searchLogic than $query->orWhere('totalAttempts', 'like', '%'.$searchTerm.'%'); is required?

**Comment by pxpm** [comment]
@LavinaHs could this be related with: https://github.com/Laravel-Backpack/CRUD/pull/3541 ??

I think it's is very possible that it does.

Let me know,
Pedro

**Comment by promatik** [comment]
Btw @pxpm, please take a final look at #3541 😅

**Comment by LavinaHs** [comment]
@pxpm Hello, this is not an issue of orderLogic, it works as it recognizes the computational column 'totalAttempts' and is able to sort by it. What it does not do, is search through it, as the computational column 'totalAttempts' does not exist in the query any more

**Comment by pxpm** [comment]
@LavinaHs we've just merged a PR that could fix your issue. 

Please in your development environment pull the `master` branch (it's not tagged yet, so a composer update will not get any update for now). You can delete `vendor/backpack/crud` folder  (if you are not overriding vendor files in that folder, I hope not 😄 ) and then do a `composer install --prefer-source` that would install the missing package (backpack/crud), but make it a git repository. You can then go into the `vendor/backpack/crud` folder a do a `git checkout master` to make sure you are in master branch. 

If it does not fix your problem, please let us know so we can have further look. 

Thanks,
Pedro

**Comment by tabacitu** [comment]
Update: the PR has been merged and tagged, so a `composer update` should do it for you @LavinaHs . Thanks for letting us know!

**Comment by LavinaHs** [comment]
Hello, sadly after composer updating i still get the same error in the log: 

Column not found: 1054 Unknown column 'totalAttempts' in 'where clause' at
