### ISSUE TITLE
[Bug] Field relationship_select causes QueryException when validation fails.

### ISSUE THREAD

**Issue by PitchRE** [Laravel-Backpack/CRUD#4027]
# Bug report

Refs;
Probably related to this PR: https://github.com/Laravel-Backpack/CRUD/pull/4002

### What I did

Created/Updated resource that contains values inside relationship_select field and validated request.
_Validation rules doesn't have anything to do  with relationship_select CRUD field._

**Field Definition**
```
        CRUD::addField([
            'name'    => 'origins',
            'label'   => 'Assosciate Origins.',
            'tab'   => 'Relationships',
            'wrapper' => [
                'class' => 'form-group col-md-6',
            ],

            'pivot_selector' => [
                'wrapper' => [
                    'class' => 'form-group col-md-6',
                ]
            ],
            'pivotFields' => [
                [
                    'name'    => 'as',
                    'type'    => 'text',
                    'wrapper' => [
                        'class' => 'form-group col-md-6',
                    ],
                ],

            ],
```

### What I expected to happen

**If validation passes:**
- Create/Update Resource

**If validation fails:**

- Redirect back with  validation errors being displayed.

### What happened
```
Illuminate\Database\QueryException
SQLSTATE[HY093]: Invalid parameter number (SQL: select * from `origins` where `id` in (2)) (View: /xxx/xxx/xxx/vendor/backpack/crud/src/resources/views/crud/fields/relationship/relationship_select.blade.php)
```

This only occurs when validation fails and relationship_select field has any data.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.0.13 (cli) (built: Nov 22 2021 09:50:43) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.13, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.77.0@148b0df9eaac9f89bebb6b6fbbb0e9874e62ecc7

### BACKPACK VERSION:
4.2.x-dev@69d7047ae60a2c45a0cd02c9e56553f42e961d72
```

**Comment by pxpm** [comment]
On it. Thanks for the report @PitchRE !

I've just tested the `relationship_select` as a single field and can confirm this does not happen due to relationship_select itself probably only when used as a pivot selector.

Be back in a few!

**Comment by pxpm** [comment]
Hey @PitchRE 

Thanks again for taking time to submit the report. I think I found the culprit.

I've submitted PR #4029 to address this issue. Please notice that the PR needs review and we are not sure yet if this is the correct/optimal way to fix this, but if you want to give it a try and let us know if it fixed for you, it could help us alot. 

I am going to close this since we have the PR, but feel free to comment here or re-open if the PR didn't fixed it for you.

Wish you the best,
Pedro

**Comment by pxpm** [comment]
Let's get back here @PitchRE !

Clearly not the same issue as in the other PR. I cannot reproduce your issue so .. let's try it again.

Can you share with me your pivot table ? I will try to setup exactly the same scenario as you.

**Comment by PitchRE** [comment]
@pxpm  Please take a look at this [repository](https://github.com/PitchRE/issue-4027). I just created brand new laravel project where I reproduced this issue.
Unfortunately I forgot to add some directories to gitignore so commit is a mess.

**Comment by pxpm** [comment]
Hey @PitchRE 

Thanks again for your support helping to fix this issue. I am still not able to reproduce it. 

Here is a .gif of me playing with your repository: https://recordit.co/diqyWa58xQ

Can you give me the exact steps to reproduce your issue ? 

Best,
Pedro

**Comment by PitchRE** [comment]
@pxpm Damn, I am speechless. If you cloned my repository, you for sure should be able to reproduce it.
Which database engine are you using?

Please take a look at https://github.com/Laravel-Backpack/CRUD/pull/4029#discussion_r774206209

**Comment by pxpm** [comment]
@PitchRE Hey there!

Thanks for the submitted code. Unfortunatelly that would only apply to the selects fields and this is a general problem of using the combination with repeatable. 

Can you make sure you don't have the backpack files in your `resources/views/vendor/backpack/crud` and are overwritting them? When they are present in that folder backpack will use that file and never pick the updated file from backpack source. 

I don't see what could be if not that. Try clearing your caches `php artisan view:clear` && `php artisan cache:clear`

Let me know,
Pedro

**Comment by PitchRE** [comment]
@pxpm

> Can you make sure you don't have the backpack files in your resources/views/vendor/backpack/crud and are overwritting them?

Yes, am sure. Currently testing on fresh laravel project. [PitchRE/issue-4027](https://github.com/PitchRE/issue-4027)

https://user-images.githubusercontent.com/45101591/147251929-43a9367f-152e-449f-b40e-02465adf1852.mp4

I don't think I made any mistakes in relationship/field definition. It's only few files so you can verify that on that repo.

Snipped I inserted bellow seems to fix it in my case. 
Although I am not sure about it, it might break in different cases ( I don't actually know how it works  under the hood...).

```php
case 'array':
// check if field have `row_key` set, if it has we are in a repeatable
// and should get the current row value
if(isset($field['row_key'])) {
if (isset($current_value[$field['row_key']]) && isset($current_value[$field['row_key']][$field['name']])) {
$current_value = array($current_value[$field['row_key']][$field['name']]);
}
}
Log::channel('daily')->debug($current_value);
/// Check if array is multidimensional.
if (count($current_value) == count($current_value, COUNT_RECURSIVE))
{
/// Do as usual. Array contains only ids.
$current_value = $connected_entity
->whereIn($connected_entity_key_name, $current_value)
->get()
->pluck($field['attribute'], $connected_entity_key_name);
}
else
{
/// We Have to loop throught array because its array of arrays.
/// Then get $field['name'] from array and create array of ids.
$arr = array();
foreach ($current_value as $key => $value) {
array_push($arr, $value[$field['name']]);
}
$current_value = $connected_entity
->whereIn($connected_entity_key_name, $arr)
->get()
->pluck($field['attribute'], $connected_entity_key_name);
}
break;
```
#### These are just my loose thoughts.
**So why sometimes `$current_value` is an multidimensional array and other times not?**
What's the intended behaviour of `$current_value`?


```php

        CRUD::addField([
            'name'    => 'characters',
            'label'   => 'Assosciate Characters with this origins.',
            'tab'   => 'Relationships',
            'wrapper' => [
                'class' => 'form-group col-md-6',
            ],

            'new_item_label'  => 'Associate Character',
            'init_rows' => 0,
            'min_rows' => 0,
            'max_rows' => 10,
        ]);
```

In this case it will work because `$current_value` is just simple array `array(1,5,7) ;`

```log
[2021-12-23 14:39:24] local.DEBUG: array (
  0 => '1',
  1 => '4',
)  
```


But as soon as I change field definition to this, it breaks

```php
        CRUD::addField([
            'name'    => 'characters',
            'label'   => 'Assosciate Characters with this origins.',
            'tab'   => 'Relationships',
            'wrapper' => [
                'class' => 'form-group col-md-6',
            ],

            'pivot_selector' => [
                'wrapper' => [
                    'class' => 'form-group col-md-6',
                ]
            ],
            'pivotFields' => [
                [
                    'name'    => 'as',
                    'type'    => 'text',
                    'wrapper' => [
                        'class' => 'form-group col-md-6',
                    ],
                ],

            ],
            'new_item_label'  => 'Associate Character',
            'init_rows' => 0,
            'min_rows' => 0,
            'max_rows' => 10,
        ]);
``` 
And Log output is way different.

```log

[2021-12-23 14:41:08] local.DEBUG: array (
  0 => '1',
)  
[2021-12-23 14:41:08] local.DEBUG: array (
  0 => '4',
)  
[2021-12-23 14:41:08] local.DEBUG: array (
  0 => 
  array (
    'characters' => '1',
    'as' => 'test char',
  ),
  1 => 
  array (
    'characters' => '4',
    'as' => 'fuuuu char',
  ),
)  

```

This multidimensional array. I guess It shouldn't be there at all ?
Because if I just return null when `$current_value` is an multidimensional array, I don't see any changes in behaviour of the field.

**Comment by pxpm** [comment]
@PitchRE that is due to the fact that the pivot selector is called `characters` and the main field, the repeatable field, is also called `characters`. So when getting from  `old()` it gets the main field `characters`, that contains the multiple pivot fields that are also called `characters`. 

https://github.com/Laravel-Backpack/CRUD/pull/4032 should probably fix this without needing this fix in the field files.

**Comment by pxpm** [comment]
This is fixed I think.

Please re-open or comment if I am wrong. 

Thanks for testing 4.2 @PitchRE , since this issue was opened alot of stuff have been added/fixed regarding relationships specially in the last days with nested relations. 

Let us know if you find something broken while using that branch :)

Pedro

**Comment by csathop-btu** [comment]
Hey @pxpm, I can confirm that this issue still exists with relationship fields which includes subfields (pivot columns), with latest backpack/crud and backpack/pro

**Comment by csathoPeter** [comment]
Hey @pxpm, I can confirm that this issue still exists with relationship fields which includes subfields (pivot columns), with latest backpack/crud and backpack/pro

**Comment by csathoPeter** [comment]
Adding 
  $pivotSelectorField['name'] = $field['name'].'-subfield';
to vendor/backpack/crud/src/app/Library/CrudPanel/Traits/Relationships.php:291 seems to fix the issue

**Comment by tabacitu** [comment]
@csathoPeter are you getting this when using the 4.2 branch, or after upgrading to v5?

**Comment by csathop-btu** [comment]
Hey Cristian,

I’m on V5.


Csathó Péter

IT vezeto
IT osztály


[cid:line_4db02253-7ead-405c-b6fe-acf447972903.png]
[cid:btusa_logo_small_8dd677cf-dc0f-49d7-a682-a4f0455fa58d.png]<http://biotechusa.com/>
1033 Budapest, Huszti út 60.
M: +36204633305
E: ***@***.******@***.***>

From: Cristian Tabacitu ***@***.***>
Date: Tuesday, 2022. March 15. 11:13
To: Laravel-Backpack/CRUD ***@***.***>
Cc: Csathó Péter ***@***.***>, Comment ***@***.***>
Subject: Re: [Laravel-Backpack/CRUD] [Bug] Field relationship_select causes QueryException when validation fails. (Issue #4027)

@csathoPeter<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FcsathoPeter&data=04%7C01%7Ccsatho.peter%40biotechusa.com%7C75583c1fb8cb48bc307c08da066c6a02%7Cc9cb5fbb48c0421ca0ce43d9de273623%7C0%7C0%7C637829359968390840%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yLQeYVpri77U3SpRjHHYVUiLBsxm4O6aMXR6cDljWeQ%3D&reserved=0> are you getting this when using the 4.2 branch, or after upgrading to v5?

—
Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLaravel-Backpack%2FCRUD%2Fissues%2F4027%23issuecomment-1067798043&data=04%7C01%7Ccsatho.peter%40biotechusa.com%7C75583c1fb8cb48bc307c08da066c6a02%7Cc9cb5fbb48c0421ca0ce43d9de273623%7C0%7C0%7C637829359968390840%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=owGzLzwPD%2BNTyioSjCWRH7hPUFjgGOuoFTA9WBdcYxg%3D&reserved=0>, or unsubscribe<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASXF5GVHZUZ4TYTSTDJ2PODVABPDPANCNFSM5KS3OA2Q&data=04%7C01%7Ccsatho.peter%40biotechusa.com%7C75583c1fb8cb48bc307c08da066c6a02%7Cc9cb5fbb48c0421ca0ce43d9de273623%7C0%7C0%7C637829359968390840%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cyLLrQkX4L1FTeoEhsfKZuQOzLQeC9SGFpp9C2LNNdI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ccsatho.peter%40biotechusa.com%7C75583c1fb8cb48bc307c08da066c6a02%7Cc9cb5fbb48c0421ca0ce43d9de273623%7C0%7C0%7C637829359968390840%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Tj%2BSNExZePH04ac6b%2Byk0EQ21lcNqz87KsYd3yVIYOk%3D&reserved=0> or Android<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ccsatho.peter%40biotechusa.com%7C75583c1fb8cb48bc307c08da066c6a02%7Cc9cb5fbb48c0421ca0ce43d9de273623%7C0%7C0%7C637829359968390840%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YakyQcfEdRw4HJxOJQRfucR%2FgEkqG03CrxnwvvBdQSk%3D&reserved=0>.

**Comment by pxpm** [comment]
@csathop-btu or @csathoPeter 👍  

Thanks, can you provide me the output of `php artisan backpack:version` and also your field definition ? 

Thanks

**Comment by tabacitu** [comment]
Bump! Can anybody please give us more information on this? Would love to get to the bottom of this - are you still seeing this issue?

**Comment by pxpm** [comment]
@tabacitu I think this is fixed for long time now. 

I am going to close and re-open if someone pings here.

Cheers
