### ISSUE TITLE
[Bug]  Column headers width is wrong if responsive table is disabled 

### ISSUE THREAD

**Issue by invibe-sk** [Laravel-Backpack/CRUD#4479]
# Bug report

### What I did

Disabled responsive table with `CRUD::disableResponsiveTable();` 

### What I expected to happen

Header column widths to be aligned with content column widths

### What happened

Header column widths are wrong. Footer column widths are ok though.

![Screenshot 2022-07-01 at 10 32 49](https://user-images.githubusercontent.com/70802334/176857977-ccb41082-70a1-4d67-b98d-b2df4dd67151.png)

### What I've already tried to fix it

Everything mentioned in #3138 (similar issue). But nothing works obviously, as this is supposed to be fixed in new version.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug is still present (using newest version)

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.0.19 (cli) (built: May 12 2022 08:50:19) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.19, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.19, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.17.0@091e287678ac723c591509ca6374e4ded4a99b1c

### BACKPACK VERSION:
5.1.0@9e1de794137ceb1ade1fa35e3b9366f97285efb3

### BACKPACK PRO VERSION:
1.1.1

Any suggestion, workaround or fix is welcome, as we're closing in on deadline. Thank you in advance

**Comment by pxpm** [comment]
Hello @invibe-sk 

That one should be fixed here: https://github.com/Laravel-Backpack/CRUD/pull/4289

Can you re-publish backpack assets (tag `--public` should be enough) (`--force` if you had already published them) that said:

`php artisan vendor:publish --provider=\"Backpack\\CRUD\\BackpackServiceProvider\" --tag=public --force`

**NOTE** this will overwrite the backpack assets in the public folder, your shouldn't be overriding them anyway, but better to write this down. 

after `php artisan cache:clear` and `php artisan optimize` 

Let me know how it goes.

**Comment by invibe-sk** [comment]
@pxpm Thank you for answer.

The issue is still present. The backpack installation is about 2 or 3 weeks old, so there was no change (according to git) after republishing assets.

**Comment by pxpm** [comment]
thanks for confirming @invibe-sk , I've also confirmed something is wrong. I will let @promatik have a look since he's the one who did the changes. 

@promatik there is a comment at the end of https://github.com/Laravel-Backpack/CRUD/pull/4289 describing this. 

@promatik from my perspective the first columns seem to be "quasi" aligned but then the column header start going more and more to the right. 
![image](https://user-images.githubusercontent.com/7188159/176864215-15da0780-8af8-4584-8cd4-bb7983ba95a6.png)

Cheers

**Comment by promatik** [comment]
Guys, great news, after hours of trial and error, I found the issue 👌
https://github.com/Laravel-Backpack/CRUD/pull/4490 is open with the fix, let's move the conversation there.
