### ISSUE TITLE
[Bug] Make Tabler the default theme again

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#5164]
In https://github.com/Laravel-Backpack/CRUD/pull/5153 I've made `CoreUIv2` the default v6 theme, for now. That's because there are just too many interface bugs right now, with Tabler. They're super-small - but put them together and it amounts to an "_unfinished_" and "_unpolished_" experience. It feels like a "_beta_" not a "_stable_" theme.

Same thing with CoreUIv4 (though to a lesser degree if you ask me - mostly because it has fewer moving parts - no dark mode etc).

So let's:
- [x] squash all Tabler bugs that matter
- [ ] ~~squash all CoreUIv4 bugs that matter~~
- [ ] change the installation command:
    - [ ] remove the  🟡 `public beta` labels;
    - [ ] make Tabler the default theme;
    - [ ] reorder the themes so its Tabler, CoreUIv4, CoreUIv2;

**Comment by tabacitu** [comment]
Fixed in https://github.com/Laravel-Backpack/CRUD/pull/5238

**Comment by dtmirror** [comment]
Hi @tabacitu 
Is there a way to get rid of the switching theme option completely? 
I set this
'showColorModeSwitcher' => false,
'layout' => 'vertical_transparent',

but the theme still shows the header on top.
TIA!
