### ISSUE TITLE
[Bug] Problem with the new initializeHasTranslations function with Spatie/Translatable

### ISSUE THREAD

**Issue by bedoz** [Laravel-Backpack/CRUD#5767]
# Bug report

Hello everyone, I did a composer update on my project with Backpack for Laravel and this package, the result is that I can no longer save any translations, for some reason the initializeHasTranslations function that casts all the translations to an array at the init of the Model is conflicting with the BackpackForLaravel library. At the moment I have overwritten the function by extending that class and disabling the merge of the casts, but it would be necessary to understand with them what is not working. I will try to report the same ticket on the package hoping to have support in one of the two packages.

For any further information, please feel free to contact me.

Thank you very much
Alex

### What I've already tried to fix it

I created the following function to override the current one:

```php
public function initializeHasTranslations(): void
{
    // $this->mergeCasts(
    //     array_fill_keys($this->getTranslatableAttributes(), 'array'),
    // );
}
```

By commenting out the code within, I bypass the problem, but obviously it's not a fix because it could cause other unknown problems at the moment.

### Is it a bug in the latest version of Backpack?

Yes

### PHP VERSION:
8.1.31

### PHP EXTENSIONS:
Core, bcmath, calendar, ctype, date, filter, hash, iconv, json, SPL, pcre, readline, Reflection, session, standard, mysqlnd, tokenizer, zip, zlib, libxml, dom, PDO, openssl, SimpleXML, xml, xmlreader, xmlwriter, curl, fileinfo, gd, intl, mbstring, exif, mysqli, Phar, pdo_mysql, sodium, xsl

### LARAVEL VERSION:
10.48.28.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.6
backpack/crud: 6.7.50
backpack/filemanager: 3.0.10
backpack/generators: v4.0.7
backpack/logmanager: v5.0.2
backpack/permissionmanager: 7.2.1
backpack/pro: 2.2.32
backpack/revise-operation: 2.0.0
backpack/settings: 3.1.1
backpack/theme-coreuiv2: 1.2.7

## Other Infos
Here is the link to issue opened also on spatie github: https://github.com/spatie/laravel-translatable/issues/487

**Comment by tabacitu** [comment]
Thanks for the report @bedoz ! Just talked to @pxpm yesterday about it, he's aware of it, working on it. He's put in a HUGE amount of effort to get this fixed, I'll let him update you here, when he has good news.

**Comment by pxpm** [comment]
Fixed in #5768 hopefully 👍

**Comment by kateengland-moore** [comment]
@pxpm I'm still experiencing the same issue, the only thing that works for me is to do the fix from the original poster, and then manually cast all translatable strings to arrays in my model.

Is anyone else still experiencing this issue after the fix?

**Comment by pxpm** [comment]
I will investigate if I left any other use case out. I've fixed what broke the test suite, maybe we are note covering some cases, I will check and get back to you guys. 👍

**Comment by kateengland-moore** [comment]
Thanks @pxpm , if it helps, rolling back `laravel-translatable` to pre- 6.10.0 resolves the issue, so I'm confident that it's related.

**Comment by pxpm** [comment]
Thanks @kateengland-moore  for bringing this to my attention. 
Yes, we were aware that there was a breaking change from **6.9.*** to **6.10.***

We caught it because our test suite started failing. We fixed the case we found in the tests, but this case had no tests so we missed it. 

I've released 6.7.53 with the fix 👍 

Let us know if you are still experiencing issues after the update. 

Cheers

**Comment by kateengland-moore** [comment]
@pxpm yep, that seems to have fixed it - thanks very much!!

**Comment by bedoz** [comment]
Hi everyone, hi @pxpm, sorry if I keep writing but it seems that something is not working.
I updated the packages to the latest version today and found that even downloading version 6.7.55 of Backpack the problem is still present, the laravel-translatable versione was 6.11.x (i don't remember the minor version right now). Bus also reverting back translatable to 6.9.3 the issue is still there.
In practice, if within the translation there is an object this is not saved as such, but it is converted into text with a json_encode.
When the field is read, it can no longer retrieve anything, giving me the empty field in the admin, I believe due to a missing json_decode or a double json_decode I don't know yet which of the two I am still trying to investigate.

The solution I found was to forcibly set in composer backpack/crud to version 6.7.52 and laravel-translatable to 6.9.3. This allowed me to restore the situation, which for a project in production was not exactly the best, but at least it returned to its normal functionality.

Unfortunately this problem is creating several small problems, I hope that this will allow us to get to the bottom of it soon.

Thank you for your support
Alex

**Comment by pxpm** [comment]
Hey @bedoz thanks for the input, please if you are having issues continue writing, maybe there is some other use case that the breaking change in spatie package created and we didn't found yet. 

Can you create a small reproduction repo with your exact use case, so that I can run with it locally and test your use case ? 

A migration, a crud controller and a model should be everything needed for us to debug your issue. 

Thanks
